name: Clarive Slack Plugin
description: The Slack notification op allows you to add Slack notifications into Clarive rules, including events and pipeline rules.
version: 1.0
url: https://github.com/clarive/cla-slack-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-slack-plugin